version: '3'
services:
  django:
    build: auth_app
    ports:
      - '8000:8000'
    volumes:
      - './db_data:/app/db'
    environment:
      DB_PATH: 'db/'


  jupyterhub:
    build: jupyterhub
    ports:
      - '8001:8000'
    volumes:
      - './oauth:/oauth'
    environment:
      OAUTH2_USERDATA_URL: http://django:8000/whoami
      OAUTH2_TOKEN_URL: http://django:8000/o/token/
      OAUTH2_AUTHORIZE_URL: http://localhost:8000/o/authorize/
      OAUTH_CLIENT_ID_PATH: /oauth/id
      OAUTH_CLIENT_SECRET_PATH: /oauth/secret
